//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class delete_employee
    {
        public int admin_num { get; set; }
        public Nullable<int> employee_number { get; set; }
    
        public virtual superadmin superadmin { get; set; }
        public virtual manager manager { get; set; }
    }
}
