//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class department
    {
        public string dname { get; set; }
        public int dnumber { get; set; }
        public string mgr_ssn { get; set; }
        public Nullable<System.DateTime> mgr_start_date { get; set; }
    }
}
