//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employee()
        {
            this.manage_employee_status = new HashSet<manage_employee_status>();
            this.manage_employee_salary = new HashSet<manage_employee_salary>();
        }
    
        public string employee_name { get; set; }
        public int employee_number { get; set; }
        public string employee_location { get; set; }
        public Nullable<int> salary { get; set; }
        public string employee_position { get; set; }
        public string employee_status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<manage_employee_status> manage_employee_status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<manage_employee_salary> manage_employee_salary { get; set; }
    }
}
