//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class employe
    {
        public string fname { get; set; }
        public string minit { get; set; }
        public string lname { get; set; }
        public string ssn { get; set; }
        public Nullable<System.DateTime> bdate { get; set; }
        public string address { get; set; }
        public string sex { get; set; }
        public Nullable<decimal> salary { get; set; }
        public string super_ssn { get; set; }
        public int dno { get; set; }
    }
}
