//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7.Controllers
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class masterEntities : DbContext
    {
        public masterEntities()
            : base("name=masterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CUSTOMER> CUSTOMERs { get; set; }
        public virtual DbSet<delete_employee> delete_employee { get; set; }
        public virtual DbSet<delete_SystemUser> delete_SystemUser { get; set; }
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<Doctor> Doctors { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<employe> employes { get; set; }
        public virtual DbSet<manage_employee_salary> manage_employee_salary { get; set; }
        public virtual DbSet<manage_employee_status> manage_employee_status { get; set; }
        public virtual DbSet<manage_manager_status> manage_manager_status { get; set; }
        public virtual DbSet<manager> managers { get; set; }
        public virtual DbSet<superadmin> superadmins { get; set; }
        public virtual DbSet<systemUser> systemUsers { get; set; }
        public virtual DbSet<MSreplication_options> MSreplication_options { get; set; }
        public virtual DbSet<spt_fallback_db> spt_fallback_db { get; set; }
        public virtual DbSet<spt_fallback_dev> spt_fallback_dev { get; set; }
        public virtual DbSet<spt_fallback_usg> spt_fallback_usg { get; set; }
        public virtual DbSet<spt_monitor> spt_monitor { get; set; }
        public virtual DbSet<spt_values> spt_values { get; set; }
    }
}
